# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the TensorRT RTX option reference from standard Doxygen comments."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HEADER = ROOT / "src" / "tensorrt_rtx_provider_options.h"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "_generated" / "provider-options.rst"

NAMESPACE_TITLES = {
    "provider_option_names": "Session provider options",
    "run_option_names": "Run options",
}
FIELD_MARKERS = {
    "description": "/// @brief",
    "type": "/// @par Type",
    "default": "/// @par Default",
    "values": "/// @par Accepted values",
}
CONSTANT_RE = re.compile(
    r'constexpr\s+const\s+char\s*\*\s*(?P<symbol>\w+)\s*=\s*"(?P<name>[^"]+)"\s*;'
)
MARKDOWN_CODE_RE = re.compile(r"(?<!`)`([^`\n]+)`(?!`)")


@dataclass(frozen=True)
class Option:
    namespace: str
    symbol: str
    name: str
    value_type: str
    default: str
    description: str
    values: str | None


def parse_options(header: Path) -> list[Option]:
    namespace: str | None = None
    fields: dict[str, str] = {}
    active_field: str | None = None
    options: list[Option] = []

    for line_number, raw_line in enumerate(
        header.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()

        if line.startswith("namespace "):
            candidate = line.removeprefix("namespace ").strip()
            namespace = candidate if candidate in NAMESPACE_TITLES else namespace
            continue

        if line.startswith("}  // namespace "):
            closed = line.removeprefix("}  // namespace ").strip()
            if closed == namespace:
                namespace = None
            continue

        field_found = False
        for field, marker in FIELD_MARKERS.items():
            if line.startswith(marker):
                fields[field] = line.removeprefix(marker).strip()
                active_field = field
                field_found = True
                break
        if field_found:
            continue
        if line == "///":
            continue
        if line.startswith("/// ") and active_field:
            content = line.removeprefix("/// ").strip()
            fields[active_field] = f"{fields[active_field]} {content}".strip()
            continue

        match = CONSTANT_RE.fullmatch(line)
        if match and namespace in NAMESPACE_TITLES:
            required = {"type", "default", "description"}
            missing = {field for field in required if not fields.get(field)}
            if missing:
                missing_text = ", ".join(sorted(missing))
                raise ValueError(
                    f"{header}:{line_number}: {match['symbol']} is missing "
                    f"option documentation fields: {missing_text}"
                )
            options.append(
                Option(
                    namespace=namespace,
                    symbol=match["symbol"],
                    name=match["name"],
                    value_type=fields["type"],
                    default=fields["default"],
                    description=fields["description"],
                    values=fields.get("values"),
                )
            )
            fields = {}
            active_field = None
            continue

        if line and not line.startswith("///"):
            fields = {}
            active_field = None

    if fields:
        raise ValueError(f"{header}: option documentation is not attached to a constant")
    if not options:
        raise ValueError(f"{header}: no documented options found")

    return options


def render(options: list[Option], header: Path) -> str:
    def to_rst(text: str) -> str:
        return MARKDOWN_CODE_RE.sub(r"``\1``", text)

    relative_header = header.resolve().relative_to(ROOT).as_posix()
    lines = [
        "..",
        "   SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.",
        "   SPDX-License-Identifier: Apache-2.0",
        "",
        "   This file is generated by docs/generate_provider_options.py.",
        f"   Source: {relative_header}",
        "",
        "Provider options",
        "================",
        "",
        "This reference is generated from the option declarations in",
        f"``{relative_header}``. Do not edit this page directly.",
        "",
        "All option values are passed to ONNX Runtime as strings.",
        "",
    ]

    for namespace, title in NAMESPACE_TITLES.items():
        lines.extend(
            [
                title,
                "-" * len(title),
                "",
                ".. list-table::",
                "   :header-rows: 1",
                "   :widths: 20 12 10 28 30",
                "",
                "   * - Option",
                "     - Type",
                "     - Default",
                "     - Description",
                "     - Accepted values",
            ]
        )
        for option in (item for item in options if item.namespace == namespace):
            lines.extend(
                [
                    f"   * - ``{option.name}``",
                    f"     - {to_rst(option.value_type)}",
                    f"     - ``{option.default.strip('`')}``",
                    f"     - {to_rst(option.description)}",
                    f"     - {to_rst(option.values) if option.values else '—'}",
                ]
            )
        lines.append("")

    return "\n".join(lines)


def generate(header: Path = DEFAULT_HEADER, output: Path = DEFAULT_OUTPUT) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(parse_options(header), header), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--header", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    generate(args.header.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
